### ISSUE TITLE
HERE pull `token_expired` error

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#1073] opened 2024-09-16 14:23 UTC
When `pull_here` and `pull_here_path` task `get_download_link` runs for more than an hour (example: DAG run 2024-09-13, 17:00:00 EDT), the token for the pull expires and subsequent retries on this task fail immediately with `token_expired` error. We could fail immediately in this case or retry from beginning of DAG.

**Comment by radumas** [comment] 2024-09-17 13:25
Duplicate of https://github.com/CityofToronto/bdit_data-sources/issues/204 

I should have added more info in that issue :|

**Closed** 2024-12-03 16:04 UTC
Labels: bug, here
